const fs = require('fs');

let content = fs.readFileSync('src/services/contentGenerator.ts', 'utf-8');

const sanitizeFunc = `
async function sanitizeQuery(rawQuery: string): Promise<string> {
  if (!process.env.GEMINI_API_KEY) return rawQuery;
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    const prompt = \`You are an SEO Query Sanitizer.
Your job is to take a raw search query (which might contain typos, bad grammar, or be a fractured search string like "what is download be aftnews") and turn it into a clean, logical, and highly readable blog post topic.
Raw Query: "\${rawQuery}"

If the query is already clean and logical, just return it as is.
If the query has typos or is illogical, fix it (e.g., "download be aftnews" -> "How to use Downloader by AFTVnews").

Return ONLY the cleaned query string, nothing else.\`;
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: { temperature: 0.1 }
    });
    return response.text?.trim() || rawQuery;
  } catch (error) {
    console.error('[Content Generator] Error in sanitizeQuery:', error);
    return rawQuery;
  }
}
`;

// Insert the new function before executeAutoContentGeneration
content = content.replace('export async function executeAutoContentGeneration', sanitizeFunc + '\nexport async function executeAutoContentGeneration');

// Now find where targetQuery is generated by generateUniqueSeoTopic
const targetReplacement = `targetQuery = await generateUniqueSeoTopic(existingTitles);
      console.log('[Content Generator] Generated unique SEO topic:', targetQuery);
    }`;

const sanitizedReplacement = `targetQuery = await generateUniqueSeoTopic(existingTitles);
      console.log('[Content Generator] Generated unique SEO topic:', targetQuery);
    } else {
      console.log(\`[Content Generator] Sanitizing raw query: "\${targetQuery}"\`);
      targetQuery = await sanitizeQuery(targetQuery);
      console.log(\`[Content Generator] Sanitized query result: "\${targetQuery}"\`);
    }`;

content = content.replace(targetReplacement, sanitizedReplacement);

fs.writeFileSync('src/services/contentGenerator.ts', content);
console.log('Sanitization applied successfully');
